### PR TITLE
fix(image): handle relative url, catch axios 404 error

### PR DESCRIPTION
**Pull request by volodymyrburdeinyi**
This pr tries to fix errors on images:
 - image src has only `//` without schema defined, it is still valid markup
 - image is not found 404, axios raised error
 
 those two errors prevented book generation to finish sucessfully

### CODE REVIEW

**Comment by volodymyrburdeinyi** [comment]
@e-adrien can you please review this pr?

**Comment by e-adrien** [comment]
Thank you for this PR.
If you can just add checks on the `verbose` option to avoid calling `console.error` when the option is `false` I'll be happy to merge it. (like https://github.com/lesjoursfr/html-to-epub/blob/7402c37f067e7ac6168973a9a08eb98214b20ee4/src/index.ts#L713)

**Comment by volodymyrburdeinyi** [comment]
> Thank you for this PR. If you can just add checks on the `verbose` option to avoid calling `console.error` when the option is `false` I'll be happy to merge it.
> 
> like:
> 
> https://github.com/lesjoursfr/html-to-epub/blob/7402c37f067e7ac6168973a9a08eb98214b20ee4/src/index.ts#L713-L715

@e-adrien 
all done, thanks for reviewing

**Comment by e-adrien** [comment]
The QC error is not related to your changes, I will fix it later.
Thank you for this PR, I'll publish a new version with this fix in the coming hours.

**Pull request merged**
